name: 'Custom JavaScript Action'
description: 'A custom action written in JavaScript'
inputs:
  name:
    description: 'The name to greet'
    required: true
runs:
  using: 'node12'
  main: 'index.js'

jobs:
  custom-js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run custom JavaScript action
        uses: ./.github/actions/custom-js-action
        with:
          name: 'GitHub Actions Workshop'